import type {
  Animal,
  EnergySnapshot,
  EnvironmentSnapshot,
  FarmEvent,
  FeedLot,
  HealthEvent,
  KpiDef,
  KpiPoint,
  NutritionRec,
  WeightRecord,
} from "./types";

export const CLOCK = new Date("2026-08-28T10:00:00.000Z");
const DAY = 24 * 60 * 60 * 1000;

function daysAgo(n: number, hour = 8) {
  const d = new Date(CLOCK.getTime() - n * DAY);
  d.setUTCHours(hour, 12, 0, 0);
  return d.toISOString();
}

export const FARM = {
  name: "OVITECH écosystème",
  region: "Hauts Plateaux — Algérie",
  flock: "Troupeau Ouled Djellal / Rembi",
  document: "OVT-PD-02 · v0.9",
};

export const BREEDS = ["Ouled Djellal", "Rembi", "Hamra", "Berbère"] as const;

export const PENS = [
  "Engraissement A",
  "Engraissement B",
  "Maternité",
  "Parc A",
  "Parc B",
  "Parc jeunes",
  "Béliers",
] as const;

export const animals: Animal[] = [
  {
    id: "an-2401",
    rfid: "E280-1160-0001",
    code: "OV-2401",
    sex: "F",
    breed: "Ouled Djellal",
    birthDate: "2024-02-11",
    weightKg: 48.2,
    bcs: 3.0,
    stage: "engraissement",
    pen: "Engraissement A",
    status: "actif",
    lastScanAt: daysAgo(0, 7),
    adgKg: 0.21,
    notes: "",
  },
  {
    id: "an-2402",
    rfid: "E280-1160-0002",
    code: "OV-2402",
    sex: "F",
    breed: "Ouled Djellal",
    birthDate: "2023-11-02",
    weightKg: 54.6,
    bcs: 3.5,
    stage: "brebis_gestation",
    pen: "Maternité",
    status: "actif",
    lastScanAt: daysAgo(1, 9),
    adgKg: 0.05,
    notes: "Gestation confirmée J+92",
  },
  {
    id: "an-2403",
    rfid: "E280-1160-0003",
    code: "OV-2403",
    sex: "F",
    breed: "Rembi",
    birthDate: "2022-12-18",
    weightKg: 61.4,
    bcs: 2.8,
    stage: "brebis_lactation",
    pen: "Maternité",
    status: "actif",
    lastScanAt: daysAgo(0, 6),
    adgKg: -0.02,
    notes: "Agnelage 18 j",
  },
  {
    id: "an-2404",
    rfid: "E280-1160-0004",
    code: "OV-2404",
    sex: "M",
    breed: "Ouled Djellal",
    birthDate: "2025-03-04",
    weightKg: 22.1,
    bcs: 2.5,
    stage: "agneau",
    pen: "Parc jeunes",
    status: "actif",
    lastScanAt: daysAgo(2, 11),
    adgKg: 0.19,
    notes: "",
  },
  {
    id: "an-2405",
    rfid: "E280-1160-0005",
    code: "OV-2405",
    sex: "M",
    breed: "Ouled Djellal",
    birthDate: "2024-08-21",
    weightKg: 34.8,
    bcs: 3.0,
    stage: "croissance",
    pen: "Parc B",
    status: "actif",
    lastScanAt: daysAgo(0, 10),
    adgKg: 0.16,
    notes: "",
  },
  {
    id: "an-2406",
    rfid: "E280-1160-0006",
    code: "OV-2406",
    sex: "M",
    breed: "Hamra",
    birthDate: "2021-09-09",
    weightKg: 86.0,
    bcs: 3.5,
    stage: "belier",
    pen: "Béliers",
    status: "actif",
    lastScanAt: daysAgo(4, 8),
    adgKg: 0,
    notes: "Reproducteur principal",
  },
  {
    id: "an-2407",
    rfid: "E280-1160-0007",
    code: "OV-2407",
    sex: "F",
    breed: "Ouled Djellal",
    birthDate: "2023-01-14",
    weightKg: 58.2,
    bcs: 3.2,
    stage: "brebis_entretien",
    pen: "Parc A",
    status: "actif",
    lastScanAt: daysAgo(3, 15),
    adgKg: 0.01,
    notes: "",
  },
  {
    id: "an-2408",
    rfid: "E280-1160-0008",
    code: "OV-2408",
    sex: "F",
    breed: "Rembi",
    birthDate: "2024-04-02",
    weightKg: 46.0,
    bcs: 2.2,
    stage: "engraissement",
    pen: "Engraissement A",
    status: "actif",
    lastScanAt: daysAgo(1, 7),
    adgKg: 0.11,
    notes: "NEC basse — suivi",
  },
  {
    id: "an-2409",
    rfid: "E280-1160-0009",
    code: "OV-2409",
    sex: "M",
    breed: "Ouled Djellal",
    birthDate: "2024-09-12",
    weightKg: 31.4,
    bcs: 3.0,
    stage: "croissance",
    pen: "Parc B",
    status: "actif",
    lastScanAt: daysAgo(0, 12),
    adgKg: 0.17,
    notes: "",
  },
  {
    id: "an-2410",
    rfid: "E280-1160-0010",
    code: "OV-2410",
    sex: "F",
    breed: "Ouled Djellal",
    birthDate: "2024-01-28",
    weightKg: null,
    bcs: 3.0,
    stage: "engraissement",
    pen: "Engraissement B",
    status: "actif",
    lastScanAt: daysAgo(6, 9),
    adgKg: null,
    notes: "Poids non saisi — recommandation bloquée",
  },
  {
    id: "an-2411",
    rfid: "E280-1160-0011",
    code: "OV-2411",
    sex: "F",
    breed: "Rembi",
    birthDate: "2022-06-20",
    weightKg: 63.8,
    bcs: 4.2,
    stage: "brebis_entretien",
    pen: "Parc A",
    status: "actif",
    lastScanAt: daysAgo(2, 16),
    adgKg: 0.03,
    notes: "NEC haute",
  },
  {
    id: "an-2412",
    rfid: "E280-1160-0012",
    code: "OV-2412",
    sex: "M",
    breed: "Ouled Djellal",
    birthDate: "2025-04-16",
    weightKg: 18.6,
    bcs: 2.8,
    stage: "agneau",
    pen: "Parc jeunes",
    status: "actif",
    lastScanAt: daysAgo(0, 8),
    adgKg: 0.23,
    notes: "",
  },
];

function wt(
  id: string,
  animalId: string,
  kg: number,
  days: number,
): WeightRecord {
  return {
    id,
    animalId,
    kg,
    at: daysAgo(days, 8),
    syncStatus: "synced",
    source: "seed",
  };
}

export const weights: WeightRecord[] = [
  wt("wt-2401-a", "an-2401", 45.3, 14),
  wt("wt-2401-b", "an-2401", 48.2, 0),
  wt("wt-2402-a", "an-2402", 53.9, 14),
  wt("wt-2402-b", "an-2402", 54.6, 1),
  wt("wt-2403-a", "an-2403", 61.7, 14),
  wt("wt-2403-b", "an-2403", 61.4, 0),
  wt("wt-2404-a", "an-2404", 19.4, 14),
  wt("wt-2404-b", "an-2404", 22.1, 2),
  wt("wt-2405-a", "an-2405", 32.6, 14),
  wt("wt-2405-b", "an-2405", 34.8, 0),
  wt("wt-2406-a", "an-2406", 86.0, 14),
  wt("wt-2406-b", "an-2406", 86.0, 4),
  wt("wt-2407-a", "an-2407", 58.1, 14),
  wt("wt-2407-b", "an-2407", 58.2, 3),
  wt("wt-2408-a", "an-2408", 44.5, 14),
  wt("wt-2408-b", "an-2408", 46.0, 1),
  wt("wt-2409-a", "an-2409", 29.0, 14),
  wt("wt-2409-b", "an-2409", 31.4, 0),
  wt("wt-2411-a", "an-2411", 63.4, 14),
  wt("wt-2411-b", "an-2411", 63.8, 2),
  wt("wt-2412-a", "an-2412", 15.4, 14),
  wt("wt-2412-b", "an-2412", 18.6, 0),
];

export const feedLots: FeedLot[] = [
  {
    id: "feed-luz",
    name: "Luzerne fanée",
    kind: "fourrage",
    stockKg: 4280,
    costPerKg: 18,
    available: true,
    origin: "Coupe locale · Hybrid Feed",
  },
  {
    id: "feed-orge",
    name: "Orge aplatie",
    kind: "concentre",
    stockKg: 1860,
    costPerKg: 42,
    available: true,
    origin: "Approvisionnement régional",
  },
  {
    id: "feed-hyb",
    name: "Mélange hybride OVITECH",
    kind: "hybride",
    stockKg: 940,
    costPerKg: 28,
    available: true,
    origin: "Unité de production hybride",
  },
  {
    id: "feed-cmv",
    name: "CMV ovin",
    kind: "mineral",
    stockKg: 126,
    costPerKg: 85,
    available: true,
    origin: "Complément minéral vitaminé",
  },
];

export const energy: EnergySnapshot = {
  solarKwhToday: 48.2,
  consumedKwhToday: 31.6,
  batteryPercent: 74,
  autonomyPercent: 82,
  status: "nominal",
  series: Array.from({ length: 14 }, (_, i) => {
    const d = new Date(CLOCK.getTime() - (13 - i) * DAY);
    const solar = 38 + ((i * 7) % 17) + (i % 3) * 2.4;
    const load = 26 + ((i * 5) % 11) + (i % 2) * 1.8;
    return {
      day: d.toISOString().slice(0, 10),
      solar: Math.round(solar * 10) / 10,
      load: Math.round(load * 10) / 10,
    };
  }),
};

/** Couche capteurs environnement (démo Q-07) : climat des parcs + orge germée.
 *  Les parcs proviennent de `PENS` — source unique, aucune liste dupliquée. */
export const environment: EnvironmentSnapshot = {
  pens: PENS.map((pen, i) => {
    const temperatureC = Math.round((19.2 + (i % 4) * 1.3) * 10) / 10;
    return {
      pen,
      temperatureC,
      humidityPercent: 56 + (i % 3) * 5,
      status: temperatureC >= 23 ? "attention" : "ok",
    };
  }),
  hydroponie: {
    name: "Orge germée — Unité hybride",
    trays: 84,
    cyclesPerDay: 2,
    stockKg: 1480,
    temperatureC: 21.4,
    humidityPercent: 68,
    lastHarvestAt: daysAgo(0, 6),
    status: "ok",
  },
};

export const kpiSeries: KpiPoint[] = Array.from({ length: 14 }, (_, i) => {
  const d = new Date(CLOCK.getTime() - (13 - i) * DAY);
  return {
    day: d.toISOString().slice(0, 10),
    adg: Math.round((0.14 + i * 0.004 + (i % 3) * 0.01) * 1000) / 1000,
    feedCost: 210 - i * 2.4,
    identified: 78 + i * 1.4,
  };
});

export const recs: NutritionRec[] = [
  {
    id: "rec-2403",
    animalId: "an-2403",
    createdAt: daysAgo(0, 6),
    engineVersion: "DDNE-REF-0.9",
    ration: {
      forageKg: 1.4,
      concentrateKg: 0.9,
      mineralG: 30,
      waterL: 8.0,
      cpPercent: 14.6,
      meMj: 23.2,
      dmiKg: 2.3,
    },
    notes: [
      "Recommandation d'aide à la décision — l'exécution reste humaine.",
      "Lactation : fractionner le concentré en 2 repas.",
    ],
    confidence: "haute",
    missingInputs: [],
    evidence: [
      "Identité OV-2403 / RFID E280-1160-0003",
      "Stade brebis_lactation · race Rembi",
      "Moteur DDNE-REF-0.9 — règles déterministes, non IA",
    ],
    syncStatus: "synced",
    approvedBy: "Resp. production",
    servedAt: daysAgo(0, 8),
    servedBy: "Opérateur terrain",
  },
  {
    id: "rec-2401",
    animalId: "an-2401",
    createdAt: daysAgo(0, 7),
    engineVersion: "DDNE-REF-0.9",
    ration: {
      forageKg: 1.0,
      concentrateKg: 0.9,
      mineralG: 17,
      waterL: 5.1,
      cpPercent: 14.8,
      meMj: 19.8,
      dmiKg: 1.9,
    },
    notes: [
      "Recommandation d'aide à la décision — l'exécution reste humaine.",
      "Objectif carcasse : maintenir le GMQ sans dépasser NEC 4.",
    ],
    confidence: "haute",
    missingInputs: [],
    evidence: [
      "Identité OV-2401 / RFID E280-1160-0001",
      "Stade engraissement · race Ouled Djellal",
      "Moteur DDNE-REF-0.9 — règles déterministes, non IA",
    ],
    syncStatus: "pending",
    approvedBy: null,
    servedAt: null,
    servedBy: null,
  },
  {
    id: "rec-2408",
    animalId: "an-2408",
    createdAt: daysAgo(1, 7),
    engineVersion: "DDNE-REF-0.9",
    ration: {
      forageKg: 1.0,
      concentrateKg: 0.9,
      mineralG: 16,
      waterL: 4.9,
      cpPercent: 14.8,
      meMj: 19.8,
      dmiKg: 1.9,
    },
    notes: [
      "NEC basse : ration majorée pour reconstituer les réserves.",
      "Recommandation d'aide à la décision — l'exécution reste humaine.",
    ],
    confidence: "haute",
    missingInputs: [],
    evidence: [
      "Identité OV-2408 / RFID E280-1160-0008",
      "Stade engraissement · race Rembi",
      "Moteur DDNE-REF-0.9 — règles déterministes, non IA",
    ],
    syncStatus: "synced",
    approvedBy: null,
    servedAt: null,
    servedBy: null,
  },
  {
    id: "rec-2410",
    animalId: "an-2410",
    createdAt: daysAgo(6, 9),
    engineVersion: "DDNE-REF-0.9",
    ration: null,
    notes: [
      "Recommandation non émise : une entrée obligatoire est absente.",
      "Le moteur refuse d'inventer une ration sans identité nutritionnelle complète.",
    ],
    confidence: "insuffisante",
    missingInputs: ["poids vif (kg)"],
    evidence: [
      "Identité OV-2410 / RFID E280-1160-0010",
      "Stade engraissement · race Ouled Djellal",
      "Moteur DDNE-REF-0.9 — règles déterministes, non IA",
    ],
    syncStatus: "local",
    approvedBy: null,
    servedAt: null,
    servedBy: null,
  },
];

export const events: FarmEvent[] = [
  {
    id: "ev-1",
    type: "scan",
    animalId: "an-2401",
    at: daysAgo(0, 7),
    label: "Scan RFID OV-2401",
    detail: "Identité confirmée · Engraissement A",
    syncStatus: "synced",
  },
  {
    id: "ev-2",
    type: "recommandation",
    animalId: "an-2403",
    at: daysAgo(0, 6),
    label: "Ration émise OV-2403",
    detail: "DDNE-REF-0.9 · confiance haute",
    syncStatus: "synced",
  },
  {
    id: "ev-2b",
    type: "distribution",
    animalId: "an-2403",
    at: daysAgo(0, 8),
    label: "Ration distribuée OV-2403",
    detail: "1.4 kg fourrage · 0.9 kg concentré · exécution humaine",
    syncStatus: "synced",
  },
  {
    id: "ev-3",
    type: "saisie",
    animalId: "an-2405",
    at: daysAgo(0, 10),
    label: "Poids saisi OV-2405",
    detail: "34.8 kg · NEC 3.0",
    syncStatus: "pending",
  },
];

export const healthEvents: HealthEvent[] = [
  {
    id: "he-1",
    animalId: "an-2402",
    type: "examen",
    at: daysAgo(1, 9),
    by: "Resp. production",
    note: "Gestation confirmée J+92 — contrôle de routine.",
    syncStatus: "synced",
  },
  {
    id: "he-2",
    animalId: "an-2408",
    type: "examen",
    at: daysAgo(2, 7),
    by: "Opérateur terrain",
    note: "NEC 2.2 — suivi alimentaire engagé, pas de geste médical.",
    syncStatus: "synced",
  },
  {
    id: "he-3",
    animalId: "an-2410",
    type: "observation",
    at: daysAgo(6, 9),
    by: "Resp. production",
    note: "Sortie moteur refusée (poids absent) — signalement à revoir.",
    syncStatus: "pending",
  },
];

export const KPI_DICTIONARY: KpiDef[] = [
  {
    id: "KPI-01",
    name: "Troupeau actif",
    formula: "COUNT(animaux WHERE statut = actif)",
    source: "Registre individuel local",
    baseline: "Effectif OVITECH écosystème au démarrage MVP",
    target: "TBD — Q-04 / Q-09",
    pillar: "Connected Livestock Intelligence",
  },
  {
    id: "KPI-02",
    name: "Couverture RFID",
    formula: "Animaux actifs avec tag / effectif actif",
    source: "Identité RFID rattachée au dossier",
    baseline: "100 % sur le troupeau pilote tagué",
    target: "TBD — BO-04",
    pillar: "Connected Livestock Intelligence",
  },
  {
    id: "KPI-03",
    name: "GMQ moyen",
    formula: "Δ poids / Δ jours entre deux pesées valides",
    source: "Historique de poids individuel",
    baseline: "Série 14 j OVITECH écosystème",
    target: "TBD — BO-02",
    pillar: "Data-Driven Nutrition Engine",
  },
  {
    id: "KPI-04",
    name: "Décisions data-driven",
    formula: "Rations émises / (rations + refus)",
    source: "Sorties DDNE-REF-0.9",
    baseline: "Non mesuré avant le moteur",
    target: "TBD — BO-03",
    pillar: "Data-Driven Nutrition Engine",
  },
  {
    id: "KPI-05",
    name: "Coût ration (sorties)",
    formula: "Σ (kg fourrage × prix + kg concentré × prix)",
    source: "Lots Hybrid Feed × ration",
    baseline: "Coût lots du jour, sans objectif chiffré",
    target: "TBD — BO-01",
    pillar: "Hybrid Feed Production",
  },
  {
    id: "KPI-06",
    name: "Couverture fourragère",
    formula: "Stock fourrage+hybride disponible / besoin journalier estimé",
    source: "Lots + dernières rations",
    baseline: "Stocks OVITECH écosystème",
    target: "TBD — BO-07 / Q-08",
    pillar: "Hybrid Feed Production",
  },
  {
    id: "KPI-07",
    name: "Autonomie énergétique",
    formula: "Capacité utile / charge critique (représentation limitée)",
    source: "Snapshot Smart Energy Management",
    baseline: "Journée type 28/08/2026",
    target: "TBD — BO-08 / Q-08",
    pillar: "Smart Energy Management",
  },
  {
    id: "KPI-08",
    name: "File locale",
    formula: "Événements/rations en local, attente, échec ou conflit",
    source: "États de synchro",
    baseline: "Aucun silent drop",
    target: "TBD — TO-03 / Q-05",
    pillar: "Offline First",
  },
];
