/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EcosystemeRouteImport } from './routes/ecosysteme'
import { Route as EnergieRouteImport } from './routes/energie'
import { Route as FourrageRouteImport } from './routes/fourrage'
import { Route as IndicateursRouteImport } from './routes/indicateurs'
import { Route as InvestisseursRouteImport } from './routes/investisseurs'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as JourneeRouteImport } from './routes/journee'
import { Route as LabelRouteImport } from './routes/label'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as PreuveRouteImport } from './routes/preuve'
import { Route as RationRouteImport } from './routes/ration'
import { Route as SanteRouteImport } from './routes/sante'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TroupeauRouteImport } from './routes/troupeau'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as EcosystemeIndexRouteImport } from './routes/ecosysteme.index'
import { Route as EcosystemeBalanceRouteImport } from './routes/ecosysteme.balance'
import { Route as EcosystemeCamerasRouteImport } from './routes/ecosysteme.cameras'
import { Route as EcosystemeIotRouteImport } from './routes/ecosysteme.iot'
import { Route as EcosystemePortailsRouteImport } from './routes/ecosysteme.portails'
import { Route as TroupeauIndexRouteImport } from './routes/troupeau.index'
import { Route as TroupeauIdRouteImport } from './routes/troupeau.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemeRoute = EcosystemeRouteImport.update({
  id: '/ecosysteme',
  path: '/ecosysteme',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergieRoute = EnergieRouteImport.update({
  id: '/energie',
  path: '/energie',
  getParentRoute: () => rootRouteImport,
} as any)
const FourrageRoute = FourrageRouteImport.update({
  id: '/fourrage',
  path: '/fourrage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndicateursRoute = IndicateursRouteImport.update({
  id: '/indicateurs',
  path: '/indicateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestisseursRoute = InvestisseursRouteImport.update({
  id: '/investisseurs',
  path: '/investisseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneeRoute = JourneeRouteImport.update({
  id: '/journee',
  path: '/journee',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelRoute = LabelRouteImport.update({
  id: '/label',
  path: '/label',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const PreuveRoute = PreuveRouteImport.update({
  id: '/preuve',
  path: '/preuve',
  getParentRoute: () => rootRouteImport,
} as any)
const RationRoute = RationRouteImport.update({
  id: '/ration',
  path: '/ration',
  getParentRoute: () => rootRouteImport,
} as any)
const SanteRoute = SanteRouteImport.update({
  id: '/sante',
  path: '/sante',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TroupeauRoute = TroupeauRouteImport.update({
  id: '/troupeau',
  path: '/troupeau',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemeIndexRoute = EcosystemeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EcosystemeRoute,
} as any)
const EcosystemeBalanceRoute = EcosystemeBalanceRouteImport.update({
  id: '/balance',
  path: '/balance',
  getParentRoute: () => EcosystemeRoute,
} as any)
const EcosystemeCamerasRoute = EcosystemeCamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => EcosystemeRoute,
} as any)
const EcosystemeIotRoute = EcosystemeIotRouteImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => EcosystemeRoute,
} as any)
const EcosystemePortailsRoute = EcosystemePortailsRouteImport.update({
  id: '/portails',
  path: '/portails',
  getParentRoute: () => EcosystemeRoute,
} as any)
const TroupeauIndexRoute = TroupeauIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TroupeauRoute,
} as any)
const TroupeauIdRoute = TroupeauIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TroupeauRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ecosysteme': typeof EcosystemeRouteWithChildren
  '/energie': typeof EnergieRoute
  '/fourrage': typeof FourrageRoute
  '/indicateurs': typeof IndicateursRoute
  '/investisseurs': typeof InvestisseursRoute
  '/journal': typeof JournalRoute
  '/journee': typeof JourneeRoute
  '/label': typeof LabelRoute
  '/nutrition': typeof NutritionRoute
  '/preuve': typeof PreuveRoute
  '/ration': typeof RationRoute
  '/sante': typeof SanteRoute
  '/scan': typeof ScanRoute
  '/sync': typeof SyncRoute
  '/team': typeof TeamRoute
  '/troupeau': typeof TroupeauRouteWithChildren
  '/verification': typeof VerificationRoute
  '/vision': typeof VisionRoute
  '/ecosysteme/balance': typeof EcosystemeBalanceRoute
  '/ecosysteme/cameras': typeof EcosystemeCamerasRoute
  '/ecosysteme/iot': typeof EcosystemeIotRoute
  '/ecosysteme/portails': typeof EcosystemePortailsRoute
  '/troupeau/$id': typeof TroupeauIdRoute
  '/ecosysteme/': typeof EcosystemeIndexRoute
  '/troupeau/': typeof TroupeauIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/energie': typeof EnergieRoute
  '/fourrage': typeof FourrageRoute
  '/indicateurs': typeof IndicateursRoute
  '/investisseurs': typeof InvestisseursRoute
  '/journal': typeof JournalRoute
  '/journee': typeof JourneeRoute
  '/label': typeof LabelRoute
  '/nutrition': typeof NutritionRoute
  '/preuve': typeof PreuveRoute
  '/ration': typeof RationRoute
  '/sante': typeof SanteRoute
  '/scan': typeof ScanRoute
  '/sync': typeof SyncRoute
  '/team': typeof TeamRoute
  '/verification': typeof VerificationRoute
  '/vision': typeof VisionRoute
  '/ecosysteme/balance': typeof EcosystemeBalanceRoute
  '/ecosysteme/cameras': typeof EcosystemeCamerasRoute
  '/ecosysteme/iot': typeof EcosystemeIotRoute
  '/ecosysteme/portails': typeof EcosystemePortailsRoute
  '/troupeau/$id': typeof TroupeauIdRoute
  '/ecosysteme': typeof EcosystemeIndexRoute
  '/troupeau': typeof TroupeauIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ecosysteme': typeof EcosystemeRouteWithChildren
  '/energie': typeof EnergieRoute
  '/fourrage': typeof FourrageRoute
  '/indicateurs': typeof IndicateursRoute
  '/investisseurs': typeof InvestisseursRoute
  '/journal': typeof JournalRoute
  '/journee': typeof JourneeRoute
  '/label': typeof LabelRoute
  '/nutrition': typeof NutritionRoute
  '/preuve': typeof PreuveRoute
  '/ration': typeof RationRoute
  '/sante': typeof SanteRoute
  '/scan': typeof ScanRoute
  '/sync': typeof SyncRoute
  '/team': typeof TeamRoute
  '/troupeau': typeof TroupeauRouteWithChildren
  '/verification': typeof VerificationRoute
  '/vision': typeof VisionRoute
  '/ecosysteme/balance': typeof EcosystemeBalanceRoute
  '/ecosysteme/cameras': typeof EcosystemeCamerasRoute
  '/ecosysteme/iot': typeof EcosystemeIotRoute
  '/ecosysteme/portails': typeof EcosystemePortailsRoute
  '/troupeau/$id': typeof TroupeauIdRoute
  '/ecosysteme/': typeof EcosystemeIndexRoute
  '/troupeau/': typeof TroupeauIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ecosysteme'
    | '/energie'
    | '/fourrage'
    | '/indicateurs'
    | '/investisseurs'
    | '/journal'
    | '/journee'
    | '/label'
    | '/nutrition'
    | '/preuve'
    | '/ration'
    | '/sante'
    | '/scan'
    | '/sync'
    | '/team'
    | '/troupeau'
    | '/verification'
    | '/vision'
    | '/ecosysteme/balance'
    | '/ecosysteme/cameras'
    | '/ecosysteme/iot'
    | '/ecosysteme/portails'
    | '/troupeau/$id'
    | '/ecosysteme/'
    | '/troupeau/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/energie'
    | '/fourrage'
    | '/indicateurs'
    | '/investisseurs'
    | '/journal'
    | '/journee'
    | '/label'
    | '/nutrition'
    | '/preuve'
    | '/ration'
    | '/sante'
    | '/scan'
    | '/sync'
    | '/team'
    | '/verification'
    | '/vision'
    | '/ecosysteme/balance'
    | '/ecosysteme/cameras'
    | '/ecosysteme/iot'
    | '/ecosysteme/portails'
    | '/troupeau/$id'
    | '/ecosysteme'
    | '/troupeau'
  id:
    | '__root__'
    | '/'
    | '/ecosysteme'
    | '/energie'
    | '/fourrage'
    | '/indicateurs'
    | '/investisseurs'
    | '/journal'
    | '/journee'
    | '/label'
    | '/nutrition'
    | '/preuve'
    | '/ration'
    | '/sante'
    | '/scan'
    | '/sync'
    | '/team'
    | '/troupeau'
    | '/verification'
    | '/vision'
    | '/ecosysteme/balance'
    | '/ecosysteme/cameras'
    | '/ecosysteme/iot'
    | '/ecosysteme/portails'
    | '/troupeau/$id'
    | '/ecosysteme/'
    | '/troupeau/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EcosystemeRoute: typeof EcosystemeRouteWithChildren
  EnergieRoute: typeof EnergieRoute
  FourrageRoute: typeof FourrageRoute
  IndicateursRoute: typeof IndicateursRoute
  InvestisseursRoute: typeof InvestisseursRoute
  JournalRoute: typeof JournalRoute
  JourneeRoute: typeof JourneeRoute
  LabelRoute: typeof LabelRoute
  NutritionRoute: typeof NutritionRoute
  PreuveRoute: typeof PreuveRoute
  RationRoute: typeof RationRoute
  SanteRoute: typeof SanteRoute
  ScanRoute: typeof ScanRoute
  SyncRoute: typeof SyncRoute
  TeamRoute: typeof TeamRoute
  TroupeauRoute: typeof TroupeauRouteWithChildren
  VerificationRoute: typeof VerificationRoute
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosysteme': {
      id: '/ecosysteme'
      path: '/ecosysteme'
      fullPath: '/ecosysteme'
      preLoaderRoute: typeof EcosystemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energie': {
      id: '/energie'
      path: '/energie'
      fullPath: '/energie'
      preLoaderRoute: typeof EnergieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fourrage': {
      id: '/fourrage'
      path: '/fourrage'
      fullPath: '/fourrage'
      preLoaderRoute: typeof FourrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indicateurs': {
      id: '/indicateurs'
      path: '/indicateurs'
      fullPath: '/indicateurs'
      preLoaderRoute: typeof IndicateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investisseurs': {
      id: '/investisseurs'
      path: '/investisseurs'
      fullPath: '/investisseurs'
      preLoaderRoute: typeof InvestisseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journee': {
      id: '/journee'
      path: '/journee'
      fullPath: '/journee'
      preLoaderRoute: typeof JourneeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/label': {
      id: '/label'
      path: '/label'
      fullPath: '/label'
      preLoaderRoute: typeof LabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preuve': {
      id: '/preuve'
      path: '/preuve'
      fullPath: '/preuve'
      preLoaderRoute: typeof PreuveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ration': {
      id: '/ration'
      path: '/ration'
      fullPath: '/ration'
      preLoaderRoute: typeof RationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sante': {
      id: '/sante'
      path: '/sante'
      fullPath: '/sante'
      preLoaderRoute: typeof SanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troupeau': {
      id: '/troupeau'
      path: '/troupeau'
      fullPath: '/troupeau'
      preLoaderRoute: typeof TroupeauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosysteme/': {
      id: '/ecosysteme/'
      path: '/'
      fullPath: '/ecosysteme/'
      preLoaderRoute: typeof EcosystemeIndexRouteImport
      parentRoute: typeof EcosystemeRoute
    }
    '/ecosysteme/balance': {
      id: '/ecosysteme/balance'
      path: '/balance'
      fullPath: '/ecosysteme/balance'
      preLoaderRoute: typeof EcosystemeBalanceRouteImport
      parentRoute: typeof EcosystemeRoute
    }
    '/ecosysteme/cameras': {
      id: '/ecosysteme/cameras'
      path: '/cameras'
      fullPath: '/ecosysteme/cameras'
      preLoaderRoute: typeof EcosystemeCamerasRouteImport
      parentRoute: typeof EcosystemeRoute
    }
    '/ecosysteme/iot': {
      id: '/ecosysteme/iot'
      path: '/iot'
      fullPath: '/ecosysteme/iot'
      preLoaderRoute: typeof EcosystemeIotRouteImport
      parentRoute: typeof EcosystemeRoute
    }
    '/ecosysteme/portails': {
      id: '/ecosysteme/portails'
      path: '/portails'
      fullPath: '/ecosysteme/portails'
      preLoaderRoute: typeof EcosystemePortailsRouteImport
      parentRoute: typeof EcosystemeRoute
    }
    '/troupeau/': {
      id: '/troupeau/'
      path: '/'
      fullPath: '/troupeau/'
      preLoaderRoute: typeof TroupeauIndexRouteImport
      parentRoute: typeof TroupeauRoute
    }
    '/troupeau/$id': {
      id: '/troupeau/$id'
      path: '/$id'
      fullPath: '/troupeau/$id'
      preLoaderRoute: typeof TroupeauIdRouteImport
      parentRoute: typeof TroupeauRoute
    }
  }
}

interface EcosystemeRouteChildren {
  EcosystemeBalanceRoute: typeof EcosystemeBalanceRoute
  EcosystemeCamerasRoute: typeof EcosystemeCamerasRoute
  EcosystemeIotRoute: typeof EcosystemeIotRoute
  EcosystemePortailsRoute: typeof EcosystemePortailsRoute
  EcosystemeIndexRoute: typeof EcosystemeIndexRoute
}

const EcosystemeRouteChildren: EcosystemeRouteChildren = {
  EcosystemeBalanceRoute: EcosystemeBalanceRoute,
  EcosystemeCamerasRoute: EcosystemeCamerasRoute,
  EcosystemeIotRoute: EcosystemeIotRoute,
  EcosystemePortailsRoute: EcosystemePortailsRoute,
  EcosystemeIndexRoute: EcosystemeIndexRoute,
}

const EcosystemeRouteWithChildren = EcosystemeRoute._addFileChildren(
  EcosystemeRouteChildren,
)

interface TroupeauRouteChildren {
  TroupeauIdRoute: typeof TroupeauIdRoute
  TroupeauIndexRoute: typeof TroupeauIndexRoute
}

const TroupeauRouteChildren: TroupeauRouteChildren = {
  TroupeauIdRoute: TroupeauIdRoute,
  TroupeauIndexRoute: TroupeauIndexRoute,
}

const TroupeauRouteWithChildren = TroupeauRoute._addFileChildren(
  TroupeauRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EcosystemeRoute: EcosystemeRouteWithChildren,
  EnergieRoute: EnergieRoute,
  FourrageRoute: FourrageRoute,
  IndicateursRoute: IndicateursRoute,
  InvestisseursRoute: InvestisseursRoute,
  JournalRoute: JournalRoute,
  JourneeRoute: JourneeRoute,
  LabelRoute: LabelRoute,
  NutritionRoute: NutritionRoute,
  PreuveRoute: PreuveRoute,
  RationRoute: RationRoute,
  SanteRoute: SanteRoute,
  ScanRoute: ScanRoute,
  SyncRoute: SyncRoute,
  TeamRoute: TeamRoute,
  TroupeauRoute: TroupeauRouteWithChildren,
  VerificationRoute: VerificationRoute,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
